### ISSUE TITLE
Add direct container backups with pre and post script support

### ISSUE THREAD

**Issue by BUR4KBEY** [BUR4KBEY/docker-auto-backup#3]
## Goal

The objective here is to establish a system for direct backups from containers as specified in the configuration file, while also enabling the execution of pre and post scripts within each container.

## Implementation

- [X] Read and parse the configuration file.
- [X] Execute `pre_build_script` and `post_build_script` scripts for each container, if specified.
- [X] Retrieve the specified files from each container to the backup folder.
- [x] Document the changes to the README.md

## Why?

Consider a scenario where you have a running PostgreSQL container and you require periodic backups. Attempting to directly volume the path to the backup container might inadvertently include unnecessary binaries, bloating the backup file size. With this feature, you can utilize pre-build scripts to generate a backup from your PostgreSQL instance and then backup the generated SQL file, ensuring only essential data is included.

## Example Configuration File

```yml
containers:
  - name: service-1
    files:
      - /data/.:/backup/service-1/data

  - name: service-2
    files:
      - /data/.:/backup/service-2/data
    pre_build_script: |
      touch /root/logs
      echo "pre-build script ran" >> /root/logs
    post_build_script: |
      echo "post-build script ran" >> /root/logs
```
